services:
  api_installation:
    build:
      context: ./backend_app
      dockerfile: Dockerfile
    container_name: api_installation
    restart: unless-stopped
    volumes:
      - ./backend_app:/app
      - ./backend_app/gunicorn.conf.py:/etc/nginx/gunicorn.conf.py
      - ./backend_app/static:/app/staticfiles
    ports:
      - "8001:8000"
    depends_on:
      - mongodb_installation
      - redis_installation
    env_file:
      - ./backend_app/.env
    networks:
      - net_installation

volumes:
  mongodb_data:
  redis_data:

networks:
  net_installation:
    driver: bridge