"""
Django settings for system_installation_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
from .mongo_setup import (
    connect_mongo
)
from datetime import timedelta
import os
import environ
import warnings 
import urllib.parse


env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env()

BASE_DIR = Path(__file__).resolve().parent.parent

REDIS_HOST = env('REDIS_HOST', default='localhost')

LOGGING_LEVEL = env('LOGGING_LEVEL', default='WARNING')

LOGGING_FILE = env('LOGGING_FILE', default='backend_app.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': LOGGING_LEVEL,
            'class': 'logging.FileHandler',
            'filename': LOGGING_FILE,
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(message)s'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': LOGGING_LEVEL,
            'propagate': True,
        },
        'celery': {
            'handlers': ['file'],
            'level': LOGGING_LEVEL,
            'propagate': True,
        },
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--i$a=heuuy55t_!15ketws1@ks01x4zc3b@0paekw7&g$7r8k7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

CSRF_COOKIE_SECURE = False  

CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_HTTPONLY = False

CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

CSRF_COOKIE_SAMESITE = None

SESSION_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = None

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'Accept',
    'x-requested-with',
    'accept',
    'origin',
    'user-agent',
    'dnt',
    'cache-control',
    'X-CSRFToken',
    'x-requested-with',
    'x-xsrf-token',
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'graphene_django',
    # 'rest_framework_simplejwt.token_blacklist',
    'api_integration',
    'api_authorization',
    # 'api_projects',
    'api_projects.apps.ApiProjectsConfig',
    'api_projects_async_task_sequence',
    'api_services.apps.ApiServicesConfig',
    'api_measurements.apps.ApiMeasurementsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'api_authorization.middleware.MongoAuthMiddleware',
    'api_authorization.middleware.MongoConnectionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'api_authorization.backends.MongoDBBackend',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


ROOT_URLCONF = 'system_installation_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, 6379, 1)], 
        },
        'CAPACITY': 1500,
    },
}

WSGI_APPLICATION = 'system_installation_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
BASE_DIR_STATIC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BACKUP_DIR = os.path.join(BASE_DIR, 'backup')

MEDIA_URL = '/backup/'
MEDIA_ROOT = BACKUP_DIR

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api_authorization.authentication.RevocationCheckJWTAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=59),  # 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ACCESS_TOKEN_LIFETIME_REMEMBER': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME_REMEMBER': timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'USER_ID_FIELD': 'id',  
    'USER_ID_CLAIM': 'user_id',
}

FRONTEND_URL = env('FRONTEND_URL', default='')
# API MAIN DATA
API_MAIN_DATA_URL = env('API_MAIN_DATA_URL', default='')
API_USER_DATA_URL = env('API_USER_DATA_URL', default='')
API_MAIN_DATA_TOKEN = env('API_MAIN_DATA_TOKEN', default='')


# Celery

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='')
CELERY_TASKS_DELAY = env('CELERY_TASKS_DELAY', default=5)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'
CELERY_ENABLE_UTC = False
CELERY_BEAT_SCHEDULE = {
    'run-task-sequence-daily': {
        'task': 'api_projects_async_task_sequence.tasks.task_sequence_daily',
        'schedule': crontab(minute=0, hour=8, day_of_week='*'),
        # 'schedule': crontab(minute='*/2', hour='7-17', day_of_week='*'),
    },
    # 'run-task-sequence-5min': {
    #     'task': 'api_projects_async_task_sequence.tasks.task_sequence_5min',
    #     'schedule': crontab(minute='*/5', hour='7-17', day_of_week='*'),
    # },
}


# AWS

AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = env('AWS_REGION', default='')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_FOLDER_PROJECTS = env('AWS_S3_FOLDER_PROJECTS', default='projects/')
AWS_S3_FOLDER_TASKS = env('AWS_S3_FOLDER_TASKS', default='tasks/')
AWS_S3_FOLDER_SERVICES = env('AWS_S3_FOLDER_SERVICES', default='services/')
AWS_S3_FOLDER_COMMENTS = env('AWS_S3_FOLDER_COMMENTS', default='comments/')
AWS_S3_FOLDER_BACKUPS = env('AWS_S3_FOLDER_BACKUPS', default='backups/mongodb/')

# INSTALLATION STAGES
PREPARATION_STAGE = env('PREPARATION_STAGE', default='Preparation')
INSTALLATION_STAGE = env('INSTALLATION_STAGE', default='Installation')
COORDINATION_STAGE = env('COORDINATION_STAGE', default='Coordination')
PERMISSION_STAGE = env('PERMISSION_STAGE', default='Permission')
CLOSING_STAGE = env('CLOSING_STAGE', default='Closing')
FINISHED_STAGE = env('FINISHED_STAGE', default='Finished')

# SERVICE STAGES
SERVICE_PREPARATION_STAGE = env('SERVICE_PREPARATION_STAGE', default='Preparation')
SERVICE_REPAIR_STAGE = env('SERVICE_REPAIR_STAGE', default='Repair')
SERVICE_CLOSING_STAGE = env('SERVICE_CLOSING_STAGE', default='Closing')
SERVICE_FINISHED_STAGE = env('SERVICE_FINISHED_STAGE', default='Finished')

# ZOHO
ZOHO_ORG_ID = env('ZOHO_ORG_ID', default='')
ZOHO_ORG_NWS_ID = env('ZOHO_ORG_NWS_ID', default='')

# PROJECTS
PROJECT_WORK = env('PROJECT_WORK', default='Work')
PROJECT_SCOPE = env('PROJECT_SCOPE', default='Scope')
PROJECT_ITEM_INSTALLATION_NAME = env('PROJECT_ITEM_INSTALLATION_NAME', default='Installation of Impact Windows and/or Doors')
PROJECT_ITEM_STRUCTURAL_NAME = env('PROJECT_ITEM_STRUCTURAL_NAME', default='Structural Modifications & Exterior Alterations')

# TASKS
TASK_START_INSTALLATION = env('TASK_START_INSTALLATION', default='Start Installation')
TASK_FINISH_INSTALLATION = env('TASK_FINISH_INSTALLATION', default='Finish Installation')
TASK_ASSIGN_INSTALLATION_CREW = env('TASK_ASSIGN_INSTALLATION_CREW', default='Assign Installation Crew')
TASK_COORDINATE_INSTALLATION_DATE = env('TASK_COORDINATE_INSTALLATION_DATE', default='Coordinate Installation Date')
TASK_COORDINATE_INSPECTION = env('TASK_COORDINATE_INSPECTION', default='Coordinate Inspection')
TASK_ORDER_IS_READY_TO_PICK_UP = env('TASK_ORDER_IS_READY_TO_PICK_UP', default='Order is ready to pick up')
TASK_PICK_UP_ORDER = env('TASK_PICK_UP_ORDER', default='Pick up Order')
TASK_COMPLETE_SATISFACTION_FORM = env('TASK_COMPLETE_SATISFACTION_FORM', default='Complete Satisfaction Form')
TASK_GENERATE_INSTALLATION_GUIDE = env('TASK_GENERATE_INSTALLATION_GUIDE', default='Generate Installation Guide')

# SERVICE TASKS
TASK_SERVICE_UPLOAD_REPAIR = env('TASK_SERVICE_UPLOAD_REPAIR', default='Upload Repair')
TASK_SERVICE_ASSIGN_CREW = env('TASK_SERVICE_ASSIGN_CREW', default='Assign Crew')
TASK_SERVICE_UPLOAD_ISSUES = env('TASK_SERVICE_UPLOAD_ISSUES', default='Upload Issues')
TASK_SERVICE_SCHEDULE_DATE = env('TASK_SERVICE_SCHEDULE_DATE', default='Schedule Date')

# USER ROLES
ROLE_SUPERADMIN = env('ROLE_SUPERADMIN', default='Superadmin')
ROLE_ADMINISTRATOR = env('ROLE_ADMINISTRATOR', default='Administrator')
ROLE_INSTALLER =env('ROLE_INSTALLER', default='Installer')
ROLE_SERVICE_STAFF = env('ROLE_SERVICE_STAFF', default='Service Staff')
ROLE_WAREHOUSE_STAFF = env('ROLE_WAREHOUSE_STAFF', default='Warehouse Staff')
ROLE_PROJECT_MANAGER = env('ROLE_PROJECT_MANAGER', default='Project Manager')

# MONGOENGINE

warnings.filterwarnings("ignore", message="MongoClient opened before fork")

MONGO_HOST = env('MONGO_HOST', default='localhost')
MONGO_PORT = int(env('MONGO_PORT', default=27017))
MONGO_USER = env('MONGO_USER', default='root')
MONGO_PASSWORD = env('MONGO_PASSWORD', default='')
MONGO_DB = env('MONGO_DB', default='')
MONGO_URI = f"mongodb://{MONGO_USER}:{urllib.parse.quote_plus(MONGO_PASSWORD)}@{MONGO_HOST}:{MONGO_PORT}/{MONGO_DB}?authSource=admin&authMechanism=SCRAM-SHA-1"

connect_mongo()


